### ISSUE TITLE
Make a final review of pre-alpha milestone

### ISSUE THREAD

**Issue by robkap94** [robkap94/OrderBuddy#38]
Okay - It's time to wrap-up everything in this milestone.

I need to ensure, whether there are still any (really) basic things, which should be done in this release. Hence:

- [x] Check whether all of the issues, for this milestone, has been done properly,
- [x] Whether app is actually working quite well,
- [x] Whether all of the existing code is commented properly,
- [x] Whether all of the testing souts are deleted,
- [x] Whether there are any additional issues,
- [x] Whether current code can be optimized (Even create additional issue for this, if necessary),
- [x] Whether there are any redundant comments,
- [x] Double-confirm above, and close the milestone.

Good luck!
