### ISSUE TITLE
Category Manager

### ISSUE THREAD

**Issue by robkap94** [robkap94/OrderBuddy#52]
As we already have Category class (for orders), we need to create small pop-up window which will be Category Manager.
Hence, it is going to be list with simple buttons (add, edit, delete).

- [x] Create pop-up window for Category Manager in the toolbar,
- [x] Establish ObservableList of categories which will be populated by loaded categories from db (addCategory in loadedDB),
- [x] Establish button add category,
- [x] Establish add functionality with similar method as it was done with orders in #35 ,
- [x] Establish button edit category,
- [x] Establish button delete category,
- [x] Ensure that in the "Create Order" you can choose categories from the dropdown list, user should not type it manually since now (AddOrderDialogController),
- [x] Ensure that above is also applied for the Edit Order. (Will be applied in feature #40 )

Additional tasks:

- [x] Adjust jUnit tests for Feature #35 ,
- [x] Change project's "Window" class into "AppWindow" to not collide with JavaFX's lib "Window" class,
- [x] From commentary below, check whether it's good idea, or not, to leave duplicated code.
